package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a single activity log entry in the SmartHome Orchestrator.
 *
 * <p>Each entry records a manual device state change, capturing when it happened,
 * which device was affected, which user owns the log, the actor's display name,
 * and a human-readable description of the action.</p>
 *
 * <p>Maps to the {@code activity_logs} table created by Flyway migration V5.
 * Implements FR-08: Aktivitätsprotokoll.</p>
 */
@Entity
@Table(name = "activity_logs")
public class ActivityLog {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Timestamp when the device state change occurred. */
    @Column(nullable = false)
    private Instant timestamp;

    /** The device that was changed. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "device_id", nullable = false)
    private Device device;

    /**
     * The user who owns this log entry (used for scoping queries).
     * This is the owner of the devices, not necessarily the actor.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Display name of the actor who performed the action. */
    @Column(name = "actor_name", nullable = false, length = 255)
    private String actorName;

    /** Human-readable description of the action performed. */
    @Column(nullable = false, length = 500)
    private String action;

    /** Default constructor required by JPA. */
    public ActivityLog() {
    }

    /**
     * Creates an ActivityLog entry with all required fields.
     *
     * @param timestamp the timestamp of the action
     * @param device    the device that was changed
     * @param user      the owning user (for scoping)
     * @param actorName the display name of the actor
     * @param action    the human-readable action description
     */
    public ActivityLog(Instant timestamp, Device device, User user, String actorName, String action) {
        this.timestamp = timestamp;
        this.device = device;
        this.user = user;
        this.actorName = actorName;
        this.action = action;
    }

    /**
     * Returns the primary key of this log entry.
     *
     * @return the log entry id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the timestamp when the action occurred.
     *
     * @return the action timestamp
     */
    public Instant getTimestamp() {
        return timestamp;
    }

    /**
     * Returns the device that was changed.
     *
     * @return the affected device
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Returns the user who owns this log entry.
     *
     * @return the owning user
     */
    public User getUser() {
        return user;
    }

    /**
     * Returns the display name of the actor who performed the action.
     *
     * @return the actor's display name
     */
    public String getActorName() {
        return actorName;
    }

    /**
     * Returns the human-readable description of the action.
     *
     * @return the action description
     */
    public String getAction() {
        return action;
    }
}
