package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a virtual smart device assigned to a room.
 *
 * <p>Devices belong to a {@link Room} and have a type and name.
 * This entity maps to the {@code devices} table created by Flyway migration V3.</p>
 *
 * <p>FR-04: add virtual smart devices specifying type and name.</p>
 */
@Entity
@Table(name = "devices")
public class Device {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The room this device belongs to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Human-readable device name (max 50 characters, unique within the room). */
    @Column(nullable = false, length = 50)
    private String name;

    /** The device type stored as its enum name string. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DeviceType type;

    /** Timestamp when the device was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Default constructor required by JPA. */
    public Device() {
    }

    /**
     * Creates a Device with all required fields.
     *
     * @param room the owning room
     * @param name the device name (max 50 characters)
     * @param type the device type
     */
    public Device(Room room, String name, DeviceType type) {
        this.room = room;
        this.name = name;
        this.type = type;
    }

    /**
     * Returns the primary key of this device.
     *
     * @return the device id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the room this device belongs to.
     *
     * @return the owning room
     */
    public Room getRoom() {
        return room;
    }

    /**
     * Returns the name of this device.
     *
     * @return the device name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this device.
     *
     * @param name the new device name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the type of this device.
     *
     * @return the device type
     */
    public DeviceType getType() {
        return type;
    }

    /**
     * Returns the timestamp when this device was created.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
