package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a virtual smart device assigned to a room.
 *
 * <p>Devices belong to a {@link Room} and have a type and name.
 * This entity maps to the {@code devices} table created by Flyway migration V3.</p>
 *
 * <p>FR-04: add virtual smart devices specifying type and name.
 * FR-06: manual device control — state fields persisted in the same table.</p>
 */
@Entity
@Table(name = "devices")
public class Device {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The room this device belongs to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Human-readable device name (max 50 characters, unique within the room). */
    @Column(nullable = false, length = 50)
    private String name;

    /** The device type stored as its enum name string. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DeviceType type;

    /** Timestamp when the device was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Whether the device is switched on. */
    @Column(name = "state_on", nullable = false)
    private boolean stateOn = false;

    /** Brightness level (0–100), used by dimmer devices. */
    @Column(nullable = false)
    private int brightness = 50;

    /** Thermostat target temperature in degrees Celsius. */
    @Column(nullable = false)
    private double temperature = 21.0;

    /** Current sensor reading. */
    @Column(name = "sensor_value", nullable = false)
    private double sensorValue = 0;

    /** Cover position: 0 = closed, 100 = open. */
    @Column(name = "cover_position", nullable = false)
    private int coverPosition = 0;

    /** Default constructor required by JPA. */
    public Device() {
    }

    /**
     * Creates a Device with all required fields.
     *
     * @param room the owning room
     * @param name the device name (max 50 characters)
     * @param type the device type
     */
    public Device(Room room, String name, DeviceType type) {
        this.room = room;
        this.name = name;
        this.type = type;
    }

    /**
     * Returns the primary key of this device.
     *
     * @return the device id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the room this device belongs to.
     *
     * @return the owning room
     */
    public Room getRoom() {
        return room;
    }

    /**
     * Returns the name of this device.
     *
     * @return the device name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this device.
     *
     * @param name the new device name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the type of this device.
     *
     * @return the device type
     */
    public DeviceType getType() {
        return type;
    }

    /**
     * Returns the timestamp when this device was created.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns whether the device is switched on.
     *
     * @return {@code true} if the device is on
     */
    public boolean isStateOn() {
        return stateOn;
    }

    /**
     * Sets whether the device is switched on.
     *
     * @param stateOn {@code true} to switch on
     */
    public void setStateOn(boolean stateOn) {
        this.stateOn = stateOn;
    }

    /**
     * Returns the brightness level (0–100).
     *
     * @return brightness percentage
     */
    public int getBrightness() {
        return brightness;
    }

    /**
     * Sets the brightness level.
     *
     * @param brightness brightness percentage (0–100)
     */
    public void setBrightness(int brightness) {
        this.brightness = brightness;
    }

    /**
     * Returns the thermostat target temperature in degrees Celsius.
     *
     * @return temperature value
     */
    public double getTemperature() {
        return temperature;
    }

    /**
     * Sets the thermostat target temperature.
     *
     * @param temperature temperature in degrees Celsius
     */
    public void setTemperature(double temperature) {
        this.temperature = temperature;
    }

    /**
     * Returns the current sensor value.
     *
     * @return sensor reading
     */
    public double getSensorValue() {
        return sensorValue;
    }

    /**
     * Sets the sensor value.
     *
     * @param sensorValue the new sensor reading
     */
    public void setSensorValue(double sensorValue) {
        this.sensorValue = sensorValue;
    }

    /**
     * Returns the cover position (0 = closed, 100 = open).
     *
     * @return cover position
     */
    public int getCoverPosition() {
        return coverPosition;
    }

    /**
     * Sets the cover position.
     *
     * @param coverPosition 0 for closed, 100 for open
     */
    public void setCoverPosition(int coverPosition) {
        this.coverPosition = coverPosition;
    }
}
