package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a home membership in the SmartHome Orchestrator.
 *
 * <p>A {@link HomeMember} record links an invited {@link User} to the primary owner
 * of a shared home. The invited user can be either {@code OWNER} or {@code MEMBER}
 * inside that home.</p>
 *
 * <p>Implements FR-13 (role model) and FR-20 (invite/revoke members).
 * Maps to the {@code home_members} table created by Flyway migration V11.</p>
 */
@Entity
@Table(name = "home_members")
public class HomeMember {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The owner who issued the invitation. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /** The invited member (UNIQUE — each user can only be member of one home). */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "member_id", nullable = false)
    private User member;

    /** Timestamp when the membership was created. */
    @Column(name = "joined_at", nullable = false)
    private LocalDateTime joinedAt = LocalDateTime.now();

    /** Role of the invited user inside the owner's home: OWNER or MEMBER. */
    @Column(name = "role", nullable = false)
    private String role = "MEMBER";

    /** Default constructor required by JPA. */
    public HomeMember() {
    }

    /**
     * Creates a new HomeMember record.
     *
     * @param owner  the user who owns the home and issued the invitation
     * @param member the user being invited as a member
     */
    public HomeMember(User owner, User member) {
        this(owner, member, "MEMBER");
    }

    /**
     * Creates a new HomeMember record with the given role.
     *
     * @param owner  the primary user whose home is shared
     * @param member the invited user
     * @param role   the invited user's role in the shared home
     */
    public HomeMember(User owner, User member, String role) {
        this.owner = owner;
        this.member = member;
        this.role = role;
    }

    /**
     * Returns the primary key of this membership.
     *
     * @return the membership id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owner of this home membership.
     *
     * @return the owner user
     */
    public User getOwner() {
        return owner;
    }

    /**
     * Returns the member of this home membership.
     *
     * @return the member user
     */
    public User getMember() {
        return member;
    }

    /**
     * Returns the timestamp when this membership was created.
     *
     * @return the joined-at timestamp
     */
    public LocalDateTime getJoinedAt() {
        return joinedAt;
    }

    /**
     * Returns the invited user's role in the shared home.
     *
     * @return {@code "OWNER"} or {@code "MEMBER"}
     */
    public String getRole() {
        return role;
    }
}
