package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a home membership in the SmartHome Orchestrator.
 *
 * <p>A {@link HomeMember} record links a member {@link User} to an owner {@link User}.
 * The {@code member} side has a UNIQUE constraint, enforcing the exclusive role model:
 * each user can be a member of at most one home at a time.</p>
 *
 * <p>Implements FR-13 (role model) and FR-20 (invite/revoke members).
 * Maps to the {@code home_members} table created by Flyway migration V11.</p>
 */
@Entity
@Table(name = "home_members")
public class HomeMember {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The owner who issued the invitation. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /** The invited member (UNIQUE — each user can only be member of one home). */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "member_id", nullable = false)
    private User member;

    /** Timestamp when the membership was created. */
    @Column(name = "joined_at", nullable = false)
    private LocalDateTime joinedAt = LocalDateTime.now();

    /** Default constructor required by JPA. */
    public HomeMember() {
    }

    /**
     * Creates a new HomeMember record.
     *
     * @param owner  the user who owns the home and issued the invitation
     * @param member the user being invited as a member
     */
    public HomeMember(User owner, User member) {
        this.owner = owner;
        this.member = member;
    }

    /**
     * Returns the primary key of this membership.
     *
     * @return the membership id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owner of this home membership.
     *
     * @return the owner user
     */
    public User getOwner() {
        return owner;
    }

    /**
     * Returns the member of this home membership.
     *
     * @return the member user
     */
    public User getMember() {
        return member;
    }

    /**
     * Returns the timestamp when this membership was created.
     *
     * @return the joined-at timestamp
     */
    public LocalDateTime getJoinedAt() {
        return joinedAt;
    }
}
