package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a room inside a user's smart home.
 *
 * <p>Rooms are owned by a {@link User} and can be created, renamed, and deleted.
 * This entity maps to the {@code rooms} database table created by Flyway migration V2.</p>
 *
 * <p>US-004: Als authentifizierter Benutzer möchte ich Räume erstellen, umbenennen
 * und löschen können, damit ich mein Zuhause strukturiert abbilden kann.</p>
 */
@Entity
@Table(name = "rooms")
public class Room {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The user who owns this room. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Human-readable name of the room (max 30 characters). */
    @Column(nullable = false, length = 30)
    private String name;

    /** Material Design icon identifier displayed in the UI. */
    @Column(nullable = false, length = 50)
    private String icon;

    /** Timestamp when the room was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Default constructor required by JPA. */
    public Room() {
    }

    /**
     * Creates a new Room with all required fields.
     *
     * @param user the owning user
     * @param name the room name (max 30 characters)
     * @param icon the Material Design icon identifier
     */
    public Room(User user, String name, String icon) {
        this.user = user;
        this.name = name;
        this.icon = icon;
    }

    /**
     * Returns the primary key of this room.
     *
     * @return the room id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the user who owns this room.
     *
     * @return the owner
     */
    public User getUser() {
        return user;
    }

    /**
     * Returns the name of this room.
     *
     * @return the room name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this room.
     * US-004: Raum umbenennen möglich
     *
     * @param name the new room name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the icon identifier of this room.
     *
     * @return the icon name
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the icon of this room.
     *
     * @param icon the new icon identifier
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Returns the timestamp when this room was created.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
