package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity representing an IF-THEN automation rule.
 *
 * <p>A rule watches a trigger device and fires an action on an action device
 * when the configured condition is met. Supported trigger types are
 * {@link TriggerType#THRESHOLD} (sensor value comparison) and
 * {@link TriggerType#EVENT} (on/off state change).</p>
 *
 * <p>Rules are evaluated reactively inside
 * {@link at.jku.se.smarthome.service.DeviceService#updateState} after every
 * {@code PATCH /state} call. This entity maps to the {@code rules} table
 * created by Flyway migration V7.</p>
 *
 * <p>Implements FR-10: Rule Engine (IF-THEN).</p>
 */
@Entity
@Table(name = "rules")
public class Rule {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User-defined display name for this rule (max 100 characters). */
    @Column(nullable = false, length = 100)
    private String name;

    /** The type of trigger that activates this rule. */
    @Enumerated(EnumType.STRING)
    @Column(name = "trigger_type", nullable = false, length = 20)
    private TriggerType triggerType;

    /** The device whose state change triggers evaluation of this rule. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "trigger_device_id", nullable = false)
    private Device triggerDevice;

    /**
     * Comparison operator for THRESHOLD rules.
     * {@code null} for EVENT rules.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "trigger_operator", length = 5)
    private TriggerOperator triggerOperator;

    /**
     * Numeric threshold value for THRESHOLD rules.
     * {@code null} for EVENT rules.
     */
    @Column(name = "trigger_threshold_value")
    private Double triggerThresholdValue;

    /** The device to control when this rule fires. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "action_device_id", nullable = false)
    private Device actionDevice;

    /**
     * The action to apply to the action device when this rule fires.
     * {@code "true"} or {@code "false"} for Switch; {@code "open"} or {@code "close"} for Shutter.
     */
    @Column(name = "action_value", nullable = false, length = 50)
    private String actionValue;

    /** Whether this rule is active. Disabled rules are stored but never evaluated. */
    @Column(nullable = false)
    private boolean enabled = true;

    /** The user who owns this rule. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Default constructor required by JPA. */
    public Rule() {
    }

    /**
     * Returns the primary key of this rule.
     *
     * @return the rule id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the display name of this rule.
     *
     * @return the rule name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this rule.
     *
     * @param name the new name (max 100 characters)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the trigger type of this rule.
     *
     * @return THRESHOLD or EVENT
     */
    public TriggerType getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the trigger type of this rule.
     *
     * @param triggerType THRESHOLD or EVENT
     */
    public void setTriggerType(TriggerType triggerType) {
        this.triggerType = triggerType;
    }

    /**
     * Returns the device whose state change triggers this rule.
     *
     * @return the trigger device
     */
    public Device getTriggerDevice() {
        return triggerDevice;
    }

    /**
     * Sets the device whose state change triggers this rule.
     *
     * @param triggerDevice the trigger device
     */
    public void setTriggerDevice(Device triggerDevice) {
        this.triggerDevice = triggerDevice;
    }

    /**
     * Returns the comparison operator for THRESHOLD rules.
     *
     * @return GT or LT, or {@code null} for EVENT rules
     */
    public TriggerOperator getTriggerOperator() {
        return triggerOperator;
    }

    /**
     * Sets the comparison operator for THRESHOLD rules.
     *
     * @param triggerOperator GT or LT; may be {@code null} for EVENT rules
     */
    public void setTriggerOperator(TriggerOperator triggerOperator) {
        this.triggerOperator = triggerOperator;
    }

    /**
     * Returns the numeric threshold value for THRESHOLD rules.
     *
     * @return threshold value, or {@code null} for EVENT rules
     */
    public Double getTriggerThresholdValue() {
        return triggerThresholdValue;
    }

    /**
     * Sets the numeric threshold value for THRESHOLD rules.
     *
     * @param triggerThresholdValue the threshold; may be {@code null} for EVENT rules
     */
    public void setTriggerThresholdValue(Double triggerThresholdValue) {
        this.triggerThresholdValue = triggerThresholdValue;
    }

    /**
     * Returns the device to control when this rule fires.
     *
     * @return the action device
     */
    public Device getActionDevice() {
        return actionDevice;
    }

    /**
     * Sets the device to control when this rule fires.
     *
     * @param actionDevice the action device
     */
    public void setActionDevice(Device actionDevice) {
        this.actionDevice = actionDevice;
    }

    /**
     * Returns the action value string describing what to do to the action device.
     *
     * @return {@code "true"}/{@code "false"} for Switch; {@code "open"}/{@code "close"} for Shutter
     */
    public String getActionValue() {
        return actionValue;
    }

    /**
     * Sets the action value string.
     *
     * @param actionValue {@code "true"}/{@code "false"} for Switch; {@code "open"}/{@code "close"} for Shutter
     */
    public void setActionValue(String actionValue) {
        this.actionValue = actionValue;
    }

    /**
     * Returns whether this rule is currently enabled.
     *
     * @return {@code true} if the rule will be evaluated on device state changes
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the enabled state of this rule.
     *
     * @param enabled {@code true} to activate, {@code false} to pause
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the user who owns this rule.
     *
     * @return the owning user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user who owns this rule.
     *
     * @param user the owning user
     */
    public void setUser(User user) {
        this.user = user;
    }
}
