package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity representing a single device-action pair within a {@link Scene}.
 *
 * <p>When a scene is activated, each {@code SceneEntry} is applied to its
 * target device using the stored {@code actionValue}. Supported values mirror
 * the rule engine conventions: {@code "true"}/{@code "false"} for switches and
 * dimmers, {@code "open"}/{@code "close"} for covers. This entity maps to the
 * {@code scene_entries} table created by Flyway migration V13.</p>
 *
 * <p>Implements FR-018: Szenen verwalten.</p>
 */
@Entity
@Table(name = "scene_entries")
public class SceneEntry {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The scene this entry belongs to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "scene_id", nullable = false)
    private Scene scene;

    /** The target device for this entry. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "device_id", nullable = false)
    private Device device;

    /**
     * The action to apply to the device when the scene is activated.
     *
     * <p>Allowed values: {@code "true"} (on), {@code "false"} (off),
     * {@code "open"} (cover 100%), {@code "close"} (cover 0%).</p>
     */
    @Column(name = "action_value", nullable = false, length = 50)
    private String actionValue;

    /** Default constructor required by JPA. */
    public SceneEntry() {
    }

    /**
     * Returns the primary key of this scene entry.
     *
     * @return the entry id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the scene this entry belongs to.
     *
     * @return the owning scene
     */
    public Scene getScene() {
        return scene;
    }

    /**
     * Sets the scene this entry belongs to.
     *
     * @param scene the owning scene
     */
    public void setScene(Scene scene) {
        this.scene = scene;
    }

    /**
     * Returns the target device for this entry.
     *
     * @return the device
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the target device for this entry.
     *
     * @param device the device to control
     */
    public void setDevice(Device device) {
        this.device = device;
    }

    /**
     * Returns the action value string for this entry.
     *
     * @return {@code "true"}, {@code "false"}, {@code "open"}, or {@code "close"}
     */
    public String getActionValue() {
        return actionValue;
    }

    /**
     * Sets the action value string for this entry.
     *
     * @param actionValue the action string to apply on activation
     */
    public void setActionValue(String actionValue) {
        this.actionValue = actionValue;
    }
}
