package at.jku.se.smarthome.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a named scene.
 *
 * <p>A scene groups one or more {@link SceneEntry} records, each describing
 * a desired state for a particular device. Activating a scene applies all
 * entries in one operation. This entity maps to the {@code scenes} table
 * created by Flyway migration V13.</p>
 *
 * <p>Implements FR-018: Szenen verwalten.</p>
 */
@Entity
@Table(name = "scenes")
public class Scene {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User-defined display name for this scene (max 100 characters). */
    @Column(nullable = false, length = 100)
    private String name;

    /** Material icon identifier shown in the UI (max 50 characters). */
    @Column(nullable = false, length = 50)
    private String icon;

    /** The user who owns this scene. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Device-action pairs that are applied when this scene is activated. */
    @OneToMany(mappedBy = "scene", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<SceneEntry> entries = new ArrayList<>();

    /** Default constructor required by JPA. */
    public Scene() {
    }

    /**
     * Returns the primary key of this scene.
     *
     * @return the scene id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the display name of this scene.
     *
     * @return the scene name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this scene.
     *
     * @param name the new name (max 100 characters)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the Material icon identifier for this scene.
     *
     * @return the icon string
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the Material icon identifier for this scene.
     *
     * @param icon the icon string
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Returns the user who owns this scene.
     *
     * @return the owning user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user who owns this scene.
     *
     * @param user the owning user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the device-action entries of this scene.
     *
     * @return mutable list of scene entries
     */
    public List<SceneEntry> getEntries() {
        return entries;
    }

    /**
     * Replaces all device-action entries of this scene.
     *
     * @param entries the new list of entries
     */
    public void setEntries(List<SceneEntry> entries) {
        this.entries.clear();
        if (entries != null) {
            this.entries.addAll(entries);
        }
    }
}
