package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity representing a recurring time-based device schedule.
 *
 * <p>A schedule defines a recurring action to be applied to a {@link Device}
 * at a specific time on selected days of the week. Execution is managed by
 * Quartz Scheduler. This entity maps to the {@code schedules} table created
 * by Flyway migration V6.</p>
 *
 * <p>Implements FR-09: Zeitpläne konfigurieren.</p>
 */
@Entity
@Table(name = "schedules")
public class Schedule {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User-defined display name for this schedule (max 100 characters). */
    @Column(nullable = false, length = 100)
    private String name;

    /** The target device for this schedule. Deleted automatically when the device is deleted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "device_id", nullable = false)
    private Device device;

    /**
     * Comma-separated uppercase Java {@link java.time.DayOfWeek} names.
     * Example: {@code "MONDAY,WEDNESDAY,FRIDAY"}.
     */
    @Column(name = "days_of_week", nullable = false, length = 100)
    private String daysOfWeek;

    /** Hour of day at which the schedule fires (0–23, server timezone). */
    @Column(nullable = false)
    private int hour;

    /** Minute of hour at which the schedule fires (0–59). */
    @Column(nullable = false)
    private int minute;

    /**
     * JSON-serialized {@link at.jku.se.smarthome.dto.DeviceStateRequest} describing
     * the device state to apply when this schedule fires.
     */
    @Column(name = "action_payload", nullable = false, columnDefinition = "TEXT")
    private String actionPayload;

    /** Whether this schedule is active. Disabled schedules are stored but not executed. */
    @Column(nullable = false)
    private boolean enabled = true;

    /** Default constructor required by JPA. */
    public Schedule() {
    }

    /**
     * Returns the primary key of this schedule.
     *
     * @return the schedule id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the display name of this schedule.
     *
     * @return the schedule name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this schedule.
     *
     * @param name the new name (max 100 characters)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the target device for this schedule.
     *
     * @return the device
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the target device for this schedule.
     *
     * @param device the device to control
     */
    public void setDevice(Device device) {
        this.device = device;
    }

    /**
     * Returns the comma-separated days of week string.
     *
     * @return days string, e.g. {@code "MONDAY,FRIDAY"}
     */
    public String getDaysOfWeek() {
        return daysOfWeek;
    }

    /**
     * Sets the comma-separated days of week string.
     *
     * @param daysOfWeek days string, e.g. {@code "MONDAY,FRIDAY"}
     */
    public void setDaysOfWeek(String daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
    }

    /**
     * Returns the hour of day at which this schedule fires (0–23).
     *
     * @return the hour
     */
    public int getHour() {
        return hour;
    }

    /**
     * Sets the hour of day at which this schedule fires.
     *
     * @param hour hour in range 0–23
     */
    public void setHour(int hour) {
        this.hour = hour;
    }

    /**
     * Returns the minute of hour at which this schedule fires (0–59).
     *
     * @return the minute
     */
    public int getMinute() {
        return minute;
    }

    /**
     * Sets the minute of hour at which this schedule fires.
     *
     * @param minute minute in range 0–59
     */
    public void setMinute(int minute) {
        this.minute = minute;
    }

    /**
     * Returns the JSON-serialized device state payload to apply on execution.
     *
     * @return the action payload JSON string
     */
    public String getActionPayload() {
        return actionPayload;
    }

    /**
     * Sets the JSON-serialized device state payload.
     *
     * @param actionPayload JSON string representing a {@code DeviceStateRequest}
     */
    public void setActionPayload(String actionPayload) {
        this.actionPayload = actionPayload;
    }

    /**
     * Returns whether this schedule is currently enabled.
     *
     * @return {@code true} if the schedule will be executed at its configured time
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the enabled state of this schedule.
     *
     * @param enabled {@code true} to activate, {@code false} to pause
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}
