package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a registered user of the SmartHome Orchestrator.
 *
 * <p>Each user has a unique email address and a bcrypt-hashed password.
 * This entity maps to the {@code users} database table created by Flyway migration V1.</p>
 */
@Entity
@Table(name = "users")
public class User {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the user. */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Unique email address used for authentication.
     * US-001: Doppelte E-Mail-Adressen werden abgelehnt.
     */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /**
     * BCrypt-hashed password.
     * US-001: Passwort wird mit bcrypt gehasht gespeichert.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /** Timestamp when the user account was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Default constructor required by JPA. */
    public User() {
    }

    /**
     * Creates a new User with all required fields.
     *
     * @param name         the display name
     * @param email        the unique email address
     * @param passwordHash the bcrypt-hashed password
     */
    public User(String name, String email, String passwordHash) {
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
    }

    /**
     * Returns the primary key of this user.
     *
     * @return the user id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the display name of this user.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this user.
     *
     * @param name the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the email address of this user.
     *
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of this user.
     *
     * @param email the new email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the bcrypt-hashed password of this user.
     *
     * @return the password hash
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * Sets the bcrypt-hashed password.
     *
     * @param passwordHash the new password hash
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Returns the timestamp when this user account was created.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
