package at.jku.se.smarthome.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing a vacation mode configuration.
 *
 * <p>A vacation mode rule assigns a {@link Schedule} to a date window with an
 * {@link VacationModeAction action}. When the window starts, the action is applied
 * and the schedule's original {@code enabled} state is captured in {@code originalEnabled}.
 * When the window expires or the rule is manually deactivated, the schedule is
 * restored to that original state.</p>
 *
 * <p>Multiple rules may exist per user simultaneously.</p>
 *
 * <p>Implements FR-21: Urlaubsmodus.</p>
 */
@Entity
@Table(name = "vacation_modes")
public class VacationMode {

    /** Primary key, auto-generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The owner of this vacation mode configuration. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The schedule that is enabled/disabled by this vacation mode. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "schedule_id", nullable = false)
    private Schedule schedule;

    /** User-defined display name for this vacation mode (max 100 characters). */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * The action to apply to the schedule when the vacation window starts.
     * {@link VacationModeAction#ENABLE} enables the schedule;
     * {@link VacationModeAction#DISABLE} disables it.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private VacationModeAction action;

    /**
     * The original {@code enabled} state of the schedule before this rule was applied.
     * {@code null} means the window has not yet started (rule not yet activated).
     * Stored on first activation and used to restore the schedule on expiry or deactivation.
     */
    @Column(name = "original_enabled")
    private Boolean originalEnabled;

    /** First day of the vacation period (inclusive). */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Last day of the vacation period (inclusive). */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /**
     * Whether this vacation mode has been permanently deactivated.
     * Once {@code true} the mode is never re-activated.
     */
    @Column(nullable = false)
    private boolean deactivated = false;

    /** Timestamp when this vacation mode was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Default constructor required by JPA. */
    public VacationMode() {
    }

    /**
     * Returns the primary key of this vacation mode.
     *
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owner of this vacation mode.
     *
     * @return the owning user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the owner of this vacation mode.
     *
     * @param user the owning user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the schedule controlled by this vacation mode.
     *
     * @return the assigned schedule
     */
    public Schedule getSchedule() {
        return schedule;
    }

    /**
     * Sets the schedule controlled by this vacation mode.
     *
     * @param schedule the schedule to assign
     */
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }

    /**
     * Returns the display name of this vacation mode.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this vacation mode.
     *
     * @param name the new name (max 100 characters)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the first day of the vacation period (inclusive).
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the first day of the vacation period.
     *
     * @param startDate the start date (inclusive)
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the last day of the vacation period (inclusive).
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the last day of the vacation period.
     *
     * @param endDate the end date (inclusive, must be &gt;= startDate)
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns whether this vacation mode has been permanently deactivated.
     *
     * @return {@code true} if permanently deactivated
     */
    public boolean isDeactivated() {
        return deactivated;
    }

    /**
     * Sets the deactivated flag.
     *
     * @param deactivated {@code true} to permanently deactivate
     */
    public void setDeactivated(boolean deactivated) {
        this.deactivated = deactivated;
    }

    /**
     * Returns the timestamp when this vacation mode was created.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the action applied to the schedule during the vacation window.
     *
     * @return the action (ENABLE or DISABLE)
     */
    public VacationModeAction getAction() {
        return action;
    }

    /**
     * Sets the action to apply to the schedule during the vacation window.
     *
     * @param action the action (ENABLE or DISABLE)
     */
    public void setAction(VacationModeAction action) {
        this.action = action;
    }

    /**
     * Returns the original {@code enabled} state of the schedule before this rule was applied,
     * or {@code null} if the vacation window has not started yet.
     *
     * @return the original enabled state, or {@code null} if not yet activated
     */
    public Boolean getOriginalEnabled() {
        return originalEnabled;
    }

    /**
     * Sets the original {@code enabled} state captured at activation time.
     *
     * @param originalEnabled the state to restore on expiry or deactivation
     */
    public void setOriginalEnabled(Boolean originalEnabled) {
        this.originalEnabled = originalEnabled;
    }
}
